In [30]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sqlalchemy import create_engine

In [16]:
# db_host = '18.136.56.185'
# username = 'dm_team'
# user_pass = 'dm_team123#'
# db_name = 'ITSM'

# conn = create_engine('mysql+pymysql://'+username+':'+user_pass+'@'+db_host)
# stmt="show databases"  #"select * from information_schema.tables"
# df0=pd.read_sql(stmt,conn)
# df0

             Database
0  information_schema
1        project_itsm

In [19]:
# db_host = '18.136.56.185'
# username = 'dm_team'
# user_pass = 'dm_team123#'
# db_name = 'project_itsm'

# conn = create_engine('mysql+pymysql://'+username+':'+user_pass+'@'+db_host+'/'+db_name)
# stmt="select * from information_schema.tables"
# df0=pd.read_sql(stmt,conn)
# df0.tail()

,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,TABLE_TYPE,ENGINE,VERSION,ROW_FORMAT,TABLE_ROWS,AVG_ROW_LENGTH,DATA_LENGTH,...,INDEX_LENGTH,DATA_FREE,AUTO_INCREMENT,CREATE_TIME,UPDATE_TIME,CHECK_TIME,TABLE_COLLATION,CHECKSUM,CREATE_OPTIONS,TABLE_COMMENT
55,def,information_schema,INNODB_SYS_FOREIGN_COLS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1748,0,...,0,0,None,2019-07-30 02:28:13,NaT,None,utf8_general_ci,None,max_rows=9597,
56,def,information_schema,INNODB_SYS_TABLES,SYSTEM VIEW,MEMORY,10,Fixed,NaN,2060,0,...,0,0,None,2019-07-30 02:28:13,NaT,None,utf8_general_ci,None,max_rows=8144,
57,def,information_schema,INNODB_BUFFER_POOL_STATS,SYSTEM VIEW,MEMORY,10,Fixed,NaN,257,0,...,0,0,None,2019-07-30 02:28:13,NaT,None,utf8_general_ci,None,max_rows=65280,
58,def,information_schema,INNODB_FT_CONFIG,SYSTEM VIEW,MEMORY,10,Fixed,NaN,1163,0,...,0,0,None,2019-07-30 02:28:13,NaT,None,utf8_general_ci,None,max_rows=14425,
59,def,project_itsm,dataset_list,BASE TABLE,InnoDB,10,Compact,41932.0,262,11026432,...,0,4194304,None,2018-07-25 13:01:11,NaT,None,latin1_swedish_ci,None,,

In [20]:
# stmt="show tables"
# df1=pd.read_sql(stmt,conn)
# df1.tail()

  Tables_in_project_itsm
0           dataset_list

In [21]:
# stmt="select * from dataset_list"
# df1=pd.read_sql(stmt,conn)
# df1.tail()

,CI_Name,CI_Cat,CI_Subcat,WBS,Incident_ID,Status,Impact,Urgency,Priority,number_cnt,...,Reopen_Time,Resolved_Time,Close_Time,Handle_Time_hrs,Closure_Code,No_of_Related_Interactions,Related_Interaction,No_of_Related_Incidents,No_of_Related_Changes,Related_Change
46601,SBA000464,application,Server Based Application,WBS000073,IM0047053,Closed,4,4,4,0.23189604,...,,31-03-2014 16:29,31-03-2014 16:29,"0,095",Other,1,SD0147021,,,
46602,SBA000461,application,Server Based Application,WBS000073,IM0047054,Closed,4,4,4,0.805153085,...,,31-03-2014 15:29,31-03-2014 15:29,"0,428333333",User error,1,SD0146967,,,
46603,LAP000019,computer,Laptop,WBS000091,IM0047055,Closed,5,5,5,0.917466294,...,,31-03-2014 15:32,31-03-2014 15:32,"0,071666667",Hardware,1,SD0146982,,,
46604,WBA000058,application,Web Based Application,WBS000073,IM0047056,Closed,4,4,4,0.701278158,...,,31-03-2014 15:42,31-03-2014 15:42,"0,116944444",Software,1,SD0146986,,,
46605,DCE000077,hardware,DataCenterEquipment,WBS000267,IM0047057,Closed,3,3,3,0.902319509,...,,31-03-2014 22:47,31-03-2014 22:47,"0,586388889",Hardware,1,SD0147088,,,

In [31]:
df1.to_csv("ABCdata.csv")

In [32]:
data=pd.read_csv("ABCdata.csv")
data.head(10)

/Users/sankhadeepchatterjee/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,CI_Name,CI_Cat,CI_Subcat,WBS,Incident_ID,Status,Impact,Urgency,Priority,...,Reopen_Time,Resolved_Time,Close_Time,Handle_Time_hrs,Closure_Code,No_of_Related_Interactions,Related_Interaction,No_of_Related_Incidents,No_of_Related_Changes,Related_Change
0,0,SUB000508,subapplication,Web Based Application,WBS000162,IM0000004,Closed,4,4,4.0,...,NaN,04-11-2013 13:50,04-11-2013 13:51,"3,87,16,91,111",Other,1.0,SD0000007,2.0,NaN,NaN
1,1,WBA000124,application,Web Based Application,WBS000088,IM0000005,Closed,3,3,3.0,...,02-12-2013 12:31,02-12-2013 12:36,02-12-2013 12:36,"4,35,47,86,389",Software,1.0,SD0000011,1.0,NaN,NaN
2,2,DTA000024,application,Desktop Application,WBS000092,IM0000006,Closed,NS,3,NaN,...,NaN,13-01-2014 15:12,13-01-2014 15:13,"4,84,31,19,444",No error - works as designed,1.0,SD0000017,NaN,NaN,NaN
3,3,WBA000124,application,Web Based Application,WBS000088,IM0000011,Closed,4,4,4.0,...,NaN,14-11-2013 09:31,14-11-2013 09:31,"4,32,18,33,333",Operator error,1.0,SD0000025,NaN,NaN,NaN
4,4,WBA000124,application,Web Based Application,WBS000088,IM0000012,Closed,4,4,4.0,...,NaN,08-11-2013 13:55,08-11-2013 13:55,"3,38,39,03,333",Other,1.0,SD0000029,NaN,NaN,NaN
5,5,WBA000124,application,Web Based Application,WBS000088,IM0000013,Closed,4,4,4.0,...,NaN,08-11-2013 13:54,08-11-2013 13:54,"3,38,34,36,944",Other,1.0,SD0000031,NaN,NaN,NaN
6,6,WBA000082,application,Web Based Application,WBS000055,IM0000014,Closed,4,4,4.0,...,NaN,27-12-2013 10:59,27-12-2013 10:59,"3,70,31,91,389",Unknown,1.0,SD0000033,NaN,NaN,NaN
7,7,WBA000124,application,Web Based Application,WBS000088,IM0000015,Closed,4,4,4.0,...,NaN,08-11-2013 14:09,08-11-2013 14:09,"3,29,46,24,167",Other,1.0,SD0000034,NaN,NaN,NaN
8,8,WBA000124,application,Web Based Application,WBS000088,IM0000017,Closed,NS,3,NaN,...,NaN,08-11-2013 14:02,08-11-2013 14:02,"0,862777778",Other,1.0,SD0000036,NaN,NaN,NaN
9,9,WBA000082,application,Web Based Application,WBS000055,IM0000018,Closed,4,4,4.0,...,NaN,08-11-2013 14:33,08-11-2013 14:35,"3,21,15,26,944",No error - works as designed,1.0,SD0000037,NaN,NaN,NaN

In [33]:
data.shape

(46606, 26)

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46606 entries, 0 to 46605
Data columns (total 26 columns):
Unnamed: 0                    46606 non-null int64
CI_Name                       46606 non-null object
CI_Cat                        46495 non-null object
CI_Subcat                     46495 non-null object
WBS                           46606 non-null object
Incident_ID                   46606 non-null object
Status                        46606 non-null object
Impact                        46606 non-null object
Urgency                       46606 non-null object
Priority                      45226 non-null float64
number_cnt                    46606 non-null float64
Category                      46606 non-null object
KB_number                     46606 non-null object
Alert_Status                  46606 non-null object
No_of_Reassignments           46605 non-null float64
Open_Time                     46606 non-null object
Reopen_Time                   2284 non-null object
Resolved_Time                 44826 non-null object
Close_Time                    46606 non-null object
Handle_Time_hrs               46605 non-null object
Closure_Code                  46146 non-null object
No_of_Related_Interactions    46492 non-null float64
Related_Interaction           46606 non-null object
No_of_Related_Incidents       1222 non-null float64
No_of_Related_Changes         560 non-null float64
Related_Change                560 non-null object
dtypes: float64(6), int64(1), object(19)
memory usage: 9.2+ MB

In [35]:
# data.isnull().sum()

In [37]:
data['Impact'].replace(to_replace='NS', value=4, inplace=True)
# data['impact'].bfill

In [39]:
data.head()

,Unnamed: 0,CI_Name,CI_Cat,CI_Subcat,WBS,Incident_ID,Status,Impact,Urgency,Priority,...,Reopen_Time,Resolved_Time,Close_Time,Handle_Time_hrs,Closure_Code,No_of_Related_Interactions,Related_Interaction,No_of_Related_Incidents,No_of_Related_Changes,Related_Change
0,0,SUB000508,subapplication,Web Based Application,WBS000162,IM0000004,Closed,4,4,4.0,...,NaN,04-11-2013 13:50,04-11-2013 13:51,"3,87,16,91,111",Other,1.0,SD0000007,2.0,NaN,NaN
1,1,WBA000124,application,Web Based Application,WBS000088,IM0000005,Closed,3,3,3.0,...,02-12-2013 12:31,02-12-2013 12:36,02-12-2013 12:36,"4,35,47,86,389",Software,1.0,SD0000011,1.0,NaN,NaN
2,2,DTA000024,application,Desktop Application,WBS000092,IM0000006,Closed,4,3,NaN,...,NaN,13-01-2014 15:12,13-01-2014 15:13,"4,84,31,19,444",No error - works as designed,1.0,SD0000017,NaN,NaN,NaN
3,3,WBA000124,application,Web Based Application,WBS000088,IM0000011,Closed,4,4,4.0,...,NaN,14-11-2013 09:31,14-11-2013 09:31,"4,32,18,33,333",Operator error,1.0,SD0000025,NaN,NaN,NaN
4,4,WBA000124,application,Web Based Application,WBS000088,IM0000012,Closed,4,4,4.0,...,NaN,08-11-2013 13:55,08-11-2013 13:55,"3,38,39,03,333",Other,1.0,SD0000029,NaN,NaN,NaN

In [46]:
data['Priority'].fillna(data['Priority'].mean(),inplace=True)

In [47]:
data.head()

,Unnamed: 0,CI_Name,CI_Cat,CI_Subcat,WBS,Incident_ID,Status,Impact,Urgency,Priority,...,Reopen_Time,Resolved_Time,Close_Time,Handle_Time_hrs,Closure_Code,No_of_Related_Interactions,Related_Interaction,No_of_Related_Incidents,No_of_Related_Changes,Related_Change
0,0,SUB000508,subapplication,Web Based Application,WBS000162,IM0000004,Closed,4,4,4.000000,...,NaN,04-11-2013 13:50,04-11-2013 13:51,"3,87,16,91,111",Other,1.0,SD0000007,2.0,NaN,NaN
1,1,WBA000124,application,Web Based Application,WBS000088,IM0000005,Closed,3,3,3.000000,...,02-12-2013 12:31,02-12-2013 12:36,02-12-2013 12:36,"4,35,47,86,389",Software,1.0,SD0000011,1.0,NaN,NaN
2,2,DTA000024,application,Desktop Application,WBS000092,IM0000006,Closed,4,3,4.215805,...,NaN,13-01-2014 15:12,13-01-2014 15:13,"4,84,31,19,444",No error - works as designed,1.0,SD0000017,NaN,NaN,NaN
3,3,WBA000124,application,Web Based Application,WBS000088,IM0000011,Closed,4,4,4.000000,...,NaN,14-11-2013 09:31,14-11-2013 09:31,"4,32,18,33,333",Operator error,1.0,SD0000025,NaN,NaN,NaN
4,4,WBA000124,application,Web Based Application,WBS000088,IM0000012,Closed,4,4,4.000000,...,NaN,08-11-2013 13:55,08-11-2013 13:55,"3,38,39,03,333",Other,1.0,SD0000029,NaN,NaN,NaN

In [63]:
data['Reopen_Time'].fillna(method='bfill',inplace=True)
data['Reopen_Time'].fillna(method='ffill',inplace=True)

In [67]:
data.sort_values(['Reopen_Time'], ascending=True)

,Unnamed: 0,CI_Name,CI_Cat,CI_Subcat,WBS,Incident_ID,Status,Impact,Urgency,Priority,...,Reopen_Time,Resolved_Time,Close_Time,Handle_Time_hrs,Closure_Code,No_of_Related_Interactions,Related_Interaction,No_of_Related_Incidents,No_of_Related_Changes,Related_Change
486,486,SBA000263,application,Server Based Application,WBS000072,IM0000567,Closed,5,5,5.000000,...,01-10-2013 09:58,01-10-2013 10:16,01-10-2013 10:16,"0,018333333",Other,1.0,SD0000787,NaN,NaN,NaN
485,485,DTA000616,application,Desktop Application,WBS000089,IM0000566,Closed,3,3,3.000000,...,01-10-2013 09:58,24-01-2014 10:44,24-01-2014 10:44,"8,54,05,55,556",Data,1.0,SD0000772,NaN,NaN,NaN
1089,1089,WBA000103,application,Web Based Application,WBS000073,IM0001187,Closed,5,5,5.000000,...,01-10-2013 10:20,28-10-2013 12:40,28-10-2013 12:40,"1,91,20,58,333",Software,1.0,SD0001512,NaN,NaN,NaN
1093,1093,WBA000008,application,Web Based Application,WBS000167,IM0001191,Closed,5,5,5.000000,...,01-10-2013 10:20,07-10-2013 15:12,07-10-2013 15:12,"4,38,21,66,667",Software,1.0,SD0001442,NaN,NaN,NaN
1092,1092,WBA000094,application,Web Based Application,WBS000073,IM0001190,Closed,5,5,5.000000,...,01-10-2013 10:20,02-10-2013 09:23,02-10-2013 09:23,"1,54,38,88,889",Other,1.0,SD0001438,NaN,NaN,NaN
1091,1091,LAP000433,computer,Laptop,WBS000091,IM0001189,Closed,5,5,5.000000,...,01-10-2013 10:20,07-10-2013 13:10,07-10-2013 13:10,"1,50,15,55,556",Hardware,1.0,SD0001515,NaN,NaN,NaN
1090,1090,SUB000286,subapplication,Server Based Application,WBS000054,IM0001188,Closed,4,3,4.215805,...,01-10-2013 10:20,31-10-2013 13:13,31-10-2013 13:13,"2,08,33,33,333",Software,1.0,SD0001513,NaN,NaN,NaN
1088,1088,SBA000759,application,Server Based Application,WBS000296,IM0001186,Closed,4,4,4.000000,...,01-10-2013 10:20,08-10-2013 14:30,08-10-2013 14:30,"1,85,16,66,667",Other,1.0,SD0001514,NaN,NaN,NaN
1087,1087,DTA000616,application,Desktop Application,WBS000092,IM0001185,Closed,4,4,4.000000,...,01-10-2013 10:20,02-10-2013 14:34,02-10-2013 14:34,"1,94,89,16,667",Referred,1.0,SD0001511,NaN,NaN,NaN
1086,1086,SBA000759,application,Server Based Application,WBS000296,IM0001184,Closed,4,4,4.000000,...,01-10-2013 10:20,03-10-2013 16:58,03-10-2013 16:58,"3,25,16,94,444",Data,1.0,SD0001510,NaN,NaN,NaN
1083,1083,SBA000607,application,Server Based Application,WBS000263,IM0001181,Closed,5,5,5.000000,...,01-10-2013 10:20,15-10-2013 23:27,15-10-2013 23:27,"1,17,79,27,778",Other,1.0,SD0001506,NaN,NaN,NaN
1082,1082,SUB000456,subapplication,Web Based Application,WBS000073,IM0001180,Closed,4,4,4.000000,...,01-10-2013 10:20,01-10-2013 14:46,01-10-2013 14:46,"9,57,44,44,444",No error - works as designed,1.0,SD0001507,NaN,NaN,NaN
1085,1085,SBA000189,application,Server Based Application,WBS000139,IM0001183,Closed,5,5,5.000000,...,01-10-2013 10:20,04-10-2013 13:59,04-10-2013 13:59,"4,02,09,44,444",Other,NaN,#N/B,NaN,NaN,NaN
1084,1084,SBA000172,application,Server Based Application,WBS000014,IM0001182,Closed,3,3,3.000000,...,01-10-2013 10:20,07-10-2013 08:05,07-10-2013 08:06,"4,48,23,05,556",Software,34.0,#MULTIVALUE,NaN,NaN,NaN
1094,1094,SBA000045,application,Server Based Application,WBS000170,IM0001192,Closed,4,4,4.000000,...,01-10-2013 10:20,02-10-2013 13:21,02-10-2013 13:21,"0,7125",User error,1.0,SD0001441,NaN,NaN,NaN
1095,1095,SBA000088,application,Server Based Application,WBS000017,IM0001193,Closed,3,3,3.000000,...,01-10-2013 10:20,04-10-2013 14:42,04-10-2013 14:42,"2,35,60,83,333",No error - works as designed,2.0,#MULTIVALUE,NaN,NaN,NaN
855,855,WBA000058,application,Web Based Application,WBS000073,IM0000950,Closed,4,4,4.000000,...,01-10-2013 10:22,10-10-2013 07:28,10-10-2013 07:28,"0,962777778",User error,1.0,SD0001179,NaN,NaN,NaN
854,854,DTA000031,application,Desktop Application,WBS000111,IM0000949,Closed,5,5,5.000000,...,01-10-2013 10:22,11-10-2013 08:43,11-10-2013 08:43,"4,81,85,27,778",No error - works as designed,1.0,SD0001178,NaN,NaN,NaN
861,861,SBA000805,application,Server Based Application,WBS000016,IM0000956,Closed,4,3,4.215805,...,01-10-2013 10:22,01-10-2013 13:44,01-10-2013 13:44,"1,68,93,88,889",Hardware,2.0,#MULTIVALUE,NaN,NaN,NaN
858,858,DTA000189,application,Desktop Application,WBS000092,IM0000953,Closed,4,4,4.000000,...,01-10-2013 10:22,07-10-2013 08:40,07-10-2013 08:40,"6,19,575",Other,1.0,SD0001208,NaN,NaN,NaN
856,856,LAP000555,computer,Laptop,WBS000091,IM0000951,Closed,5,5,5.000000,...,01-10-2013 10:22,04-10-2013 09:43,04-10-2013 09:43,"5,24,20,27,778",Other,1.0,SD0001177,NaN,NaN,NaN
857,857,DTA000015,application,Desktop Application,WBS000093,IM0000952,Closed,4,4,4.000000,...,01-10-2013 10:22,03-10-2013 16:31,03-10-2013 16:32,"4,68,53,33,333",Software,1.0,SD0001209,NaN,NaN,NaN
859,859,LAP001519,computer,Laptop,WBS000091,IM0000954,Closed,5,5,5.000000,...,01-10-2013 10:22,11-10-2013 14:57,11-10-2013 14:57,"8,96,45,83,333",Software,1.0,SD0001210,NaN,NaN,NaN
860,860,SBA000834,application,Server Based Application,WBS000223,IM0000955,Closed,4,4,4.000000,...,01-10-2013 10:22,02-10-2013 08:33,02-10-2013 08:33,"2,95,75,55,556",Software,1.0,SD0001213,NaN,NaN,NaN
937,937,DTA000056,application,Desktop Application,WBS000091,IM0001034,Closed,4,4,4.000000,...,01-10-2013 11:06,11-10-2013 09:02,11-10-2013 09:03,"1,21,38,88,889",Software,2.0,#MULTIVALUE,NaN,NaN,NaN
938,938,WBA000133,application,Web Based Application,WBS000073,IM0001035,Closed,4,4,4.000000,...,01-10-2013 11:06,01-10-2013 11:29,01-10-2013 11:29,"7,17,27,77,778",Unknown,1.0,SD0001344,NaN,NaN,NaN
940,940,SBA000263,application,Server Based Application,WBS000072,IM0001037,Closed,5,5,5.000000,...,01-10-2013 11:06,01-10-2013 10:30,01-10-2013 10:30,"0,060277778",Other,1.0,SD0001346,NaN,NaN,NaN
941,941,SAP000004,application,SAP,WBS000271,IM0001038,Closed,5,5,5.000000,...,01-10-2013 11:06,02-10-2013 11:41,02-10-2013 11:41,"1,43,69,44,444",Other,2.0,#MULTIVALUE,NaN,NaN,NaN
939,939,SAP000004,application,SAP,WBS000271,IM0001036,Closed,5,5,5.000000,...,01-10-2013 11:06,01-10-2013 12:09,01-10-2013 12:09,"1,16,88,33,333",Other,1.0,SD0001345,NaN,NaN,NaN
656,656,SBA000698,application,Server Based Application,WBS000090,IM0000746,Closed,4,4,4.000000,...,01-10-2013 11:08,11-10-2013 12:44,11-10-2013 12:44,"0,675",Software,1.0,SD0000961,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24329,24329,WBA000011,application,Web Based Application,WBS000152,IM0024586,Closed,5,5,5.000000,...,31-12-2013 11:52,03-02-2014 15:28,03-02-2014 15:29,"1,38,98,72,222",Software,1.0,SD0073471,NaN,NaN,NaN
24328,24328,SBA000462,application,Server Based Application,WBS000073,IM0024585,Closed,4,4,4.000000,...,31-12-2013 11:52,31-12-2013 08:46,31-12-2013 08:46,"3,02,44,44,444",Other,1.0,SD0073459,NaN,NaN,NaN
24324,24324,WBA000124,application,Web Based Application,WBS000088,IM0024581,Closed,4,4,4.000000,...,31-12-2013 11:52,31-12-2013 10:34,31-12-2013 10:34,"5,14,52,77,778",Software,1.0,SD0073451,NaN,NaN,NaN
24326,24326,WBA000011,application,Web Based Application,WBS000152,IM0024583,Closed,5,5,5.000000,...,31-12-2013 11:52,30-12-2013 16:07,30-12-2013 16:09,"0,1275",User error,1.0,SD0073457,NaN,NaN,NaN
24309,24309,CBA000014,application,Client Based Application,WBS000073,IM0024566,Closed,4,4,4.000000,...,31-12-2013 11:52,NaN,31-12-2013 12:10,"5,75,38,88,889",Software,1.0,SD0073532,1.0,NaN,NaN
24310,24310,WBA000058,application,Web Based Application,WBS000073,IM0024567,Closed,4,4,4.000000,...,31-12-2013 11:52,30-12-2013 15:18,30-12-2013 15:18,"0,616111111",Other,1.0,SD0073124,NaN,NaN,NaN
24311,24311,SUB000443,subapplication,Web Based Application,WBS000125,IM0024568,Closed,5,5,5.000000,...,31-12-2013 11:52,02-01-2014 10:35,02-01-2014 10:36,"1,67,33,33,333",No error - works as designed,1.0,SD0073131,NaN,NaN,NaN
24354,24354,SAP000004,application,SAP,WBS000271,IM0024612,Closed,5,5,5.000000,...,31-12-2013 11:52,02-01-2014 07:56,02-01-2014 07:56,"1,17,39,72,222",Other,2.0,#MULTIVALUE,NaN,NaN,NaN
24313,24313,WBA000107,application,Web Based Application,WBS000162,IM0024570,Closed,4,4,4.000000,...,31-12-2013 11:52,NaN,03-01-2014 15:41,"3,18,95,83,333",Other,1.0,SD0073433,NaN,NaN,NaN
24314,24314,KYB000001,hardware,Keyboard,WBS000091,IM0024571,Closed,5,5,5.000000,...,31-12-2013 11:52,30-12-2013 16:02,30-12-2013 16:02,"0,006666667",Hardware,1.0,SD0073437,NaN,NaN,NaN
24315,24315,WBA000018,application,Web Based Application,WBS000073,IM0024572,Closed,4,4,4.000000,...,31-12-2013 11:52,07-01-2014 08:46,07-01-2014 08:46,"5,82",Software,1.0,SD0073432,NaN,NaN,NaN
24316,24316,WBA000107,application,Web Based Application,WBS000162,IM0024573,Closed,4,4,4.000000,...,31-12-2013 11:52,21-02-2014 08:35,21-02-2014 08:35,"3,64,05,69,444",Software,1.0,SD0073438,NaN,NaN,NaN
24312,24312,DSK000667,computer,Desktop,WBS000091,IM0024569,Closed,5,5,5.000000,...,31-12-2013 11:52,06-01-2014 15:57,06-01-2014 15:57,"4,30,88,33,333",Software,1.0,SD0073129,NaN,NaN,NaN
24318,24318,SUB000149,subapplication,Server Based Application,WBS000162,IM0024575,Closed,4,4,4.000000,...,31-12-2013 11:52,25-03-2014 12:09,25-03-2014 12:09,"6,26,57,55,556",Other,1.0,SD0073441,NaN,NaN,NaN
24319,24319,WBA000144,application,Web Based Application,WBS000318,IM0024576,Closed,5,5,5.000000,...,31-12-2013 11:52,15-01-2014 13:39,15-01-2014 13:39,"3,44,66,66,667",Operator error,1.0,SD0073442,NaN,NaN,NaN
24320,24320,WBA000058,application,Web Based Application,WBS000073,IM0024577,Closed,4,4,4.000000,...,31-12-2013 11:52,30-12-2013 15:50,30-12-2013 15:50,"0,146388889",Software,1.0,SD0073445,NaN,NaN,NaN
24321,24321,WBA000124,application,Web Based Application,WBS000088,IM0024578,Closed,4,4,4.000000,...,31-12-2013 11:52,02-01-2014 09:25,02-01-2014 09:25,"1,47,14,16,667",Software,1.0,SD0073446,2.0,NaN,NaN
24322,24322,SAN000182,storage,SAN,WBS000128,IM0024579,Closed,5,5,5.000000,...,31-12-2013 11:52,02-01-2014 09:26,02-01-2014 09:26,"1,46,47,77,778",User manual not used,1.0,SD0073447,NaN,NaN,NaN
24323,24323,SUB000456,subapplication,Web Based Application,WBS000073,IM0024580,Closed,4,4,4.000000,...,31-12-2013 11:52,30-12-2013 16:36,30-12-2013 16:36,"0,7375",No error - works as designed,1.0,SD0073448,NaN,NaN,NaN
24325,24325,SBA000462,application,Server Based Application,WBS000073,IM0024582,Closed,4,4,4.000000,...,31-12-2013 11:52,30-12-2013 16:38,30-12-2013 16:39,"0,642777778",Software,1.0,SD0073454,NaN,NaN,NaN
24317,24317,DTA000025,application,Desktop Application,WBS000110,IM0024574,Closed,5,5,5.000000,...,31-12-2013 11:52,31-12-2013 14:39,31-12-2013 14:39,"9,67,63,88,889",Referred,1.0,SD0073435,NaN,NaN,NaN
23759,23759,SBA000462,application,Server Based Application,WBS000073,IM0024009,Closed,4,4,4.000000,...,31-12-2013 14:06,24-12-2013 13:59,24-12-2013 13:59,"0,133333333",Operator error,1.0,SD0071612,NaN,NaN,NaN
23760,23760,SBA000759,application,Server Based Application,WBS000296,IM0024010,Closed,5,5,5.000000,...,31-12-2013 14:06,24-12-2013 15:19,24-12-2013 15:19,"1,29,13,88,889",Other,1.0,SD0071621,NaN,NaN,NaN
23761,23761,SUB000456,subapplication,Web Based Application,WBS000073,IM0024011,Closed,4,4,4.000000,...,31-12-2013 14:06,24-12-2013 14:43,24-12-2013 14:43,"0,6225",Other,1.0,SD0071624,NaN,NaN,NaN
23765,23765,SUB000002,subapplication,Citrix,WBS000098,IM0024015,Closed,4,4,4.000000,...,31-12-2013 14:06,30-12-2013 13:11,30-12-2013 13:11,"2,21,43,33,333",Hardware,1.0,SD0071272,NaN,NaN,NaN
23763,23763,SBA000263,application,Server Based Application,WBS000072,IM0024013,Closed,5,5,5.000000,...,31-12-2013 14:06,15-01-2014 08:46,15-01-2014 08:46,"1,30,99,19,444",Other,1.0,SD0071718,NaN,NaN,NaN
23764,23764,SUB000456,subapplication,Web Based Application,WBS000073,IM0024014,Closed,4,4,4.000000,...,31-12-2013 14:06,24-12-2013 14:48,24-12-2013 14:49,"0,526388889",Other,1.0,SD0071634,NaN,NaN,NaN
23766,23766,WBA000018,application,Web Based Application,WBS000073,IM0024016,Closed,4,4,4.000000,...,31-12-2013 14:06,31-12-2013 14:37,31-12-2013 14:37,"1,94,27,77,778",Other,2.0,#MULTIVALUE,NaN,NaN,NaN
23762,23762,SBA000458,application,Server Based Application,WBS000073,IM0024012,Closed,4,4,4.000000,...,31-12-2013 14:06,06-01-2014 15:16,06-01-2014 15:16,"5,67,41,38,889",Other,1.0,SD0071633,NaN,NaN,NaN
23758,23758,SUB000505,subapplication,Web Based Application,WBS000162,IM0024008,Closed,4,4,4.000000,...,31-12-2013 14:06,24-12-2013 14:25,24-12-2013 14:26,"0,585555556",No error - works as designed,1.0,SD0071615,NaN,NaN,NaN

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46606 entries, 0 to 46605
Data columns (total 26 columns):
Unnamed: 0                    46606 non-null int64
CI_Name                       46606 non-null object
CI_Cat                        46495 non-null object
CI_Subcat                     46495 non-null object
WBS                           46606 non-null object
Incident_ID                   46606 non-null object
Status                        46606 non-null object
Impact                        46606 non-null object
Urgency                       46606 non-null object
Priority                      46606 non-null float64
number_cnt                    46606 non-null float64
Category                      46606 non-null object
KB_number                     46606 non-null object
Alert_Status                  46606 non-null object
No_of_Reassignments           46605 non-null float64
Open_Time                     46606 non-null object
Reopen_Time                   46606 non-null object
Resolved_Time                 44826 non-null object
Close_Time                    46606 non-null object
Handle_Time_hrs               46605 non-null object
Closure_Code                  46146 non-null object
No_of_Related_Interactions    46492 non-null float64
Related_Interaction           46606 non-null object
No_of_Related_Incidents       1222 non-null float64
No_of_Related_Changes         560 non-null float64
Related_Change                560 non-null object
dtypes: float64(6), int64(1), object(19)
memory usage: 9.2+ MB